export interface ApplianceCatalogEntry {
  categoryName: string;
  applianceTypeName: string;
  typicalPowerW: number;
  powerFactor: number;
  nominalFrequencyHz: number;
  frequencyTolerance: number;
  thdReference: number;
  harmonicSignature: string | null;
  powerPattern: 'constant' | 'cyclic' | 'variable';
}

export const APPLIANCE_CATALOG: ApplianceCatalogEntry[] = [
  {
    categoryName: 'Cooling',
    applianceTypeName: 'Inverter Air Conditioner',
    typicalPowerW: 820,
    powerFactor: 0.95,
    nominalFrequencyHz: 60,
    frequencyTolerance: 0.5,
    thdReference: 6.5,
    harmonicSignature: '{"3rd":0.06,"5th":0.03}',
    powerPattern: 'variable',
  },
  {
    categoryName: 'Cooling',
    applianceTypeName: 'Electric Fan',
    typicalPowerW: 75,
    powerFactor: 0.9,
    nominalFrequencyHz: 60,
    frequencyTolerance: 0.5,
    thdReference: 5,
    harmonicSignature: '{"3rd":0.03}',
    powerPattern: 'constant',
  },
  {
    categoryName: 'Kitchen',
    applianceTypeName: 'Refrigerator',
    typicalPowerW: 150,
    powerFactor: 0.8,
    nominalFrequencyHz: 60,
    frequencyTolerance: 0.5,
    thdReference: 10,
    harmonicSignature: '{"3rd":0.09,"5th":0.05}',
    powerPattern: 'cyclic',
  },
  {
    categoryName: 'Kitchen',
    applianceTypeName: 'Panasonic NR-BP8515N Inverter Refrigerator',
    typicalPowerW: 95,
    powerFactor: 0.86,
    nominalFrequencyHz: 60,
    frequencyTolerance: 0.5,
    thdReference: 7.8,
    harmonicSignature: '{"3rd":0.05,"5th":0.03}',
    powerPattern: 'cyclic',
  },
  {
    categoryName: 'Kitchen',
    applianceTypeName: 'Rice Cooker',
    typicalPowerW: 700,
    powerFactor: 0.99,
    nominalFrequencyHz: 60,
    frequencyTolerance: 0.4,
    thdReference: 3,
    harmonicSignature: '{"3rd":0.02}',
    powerPattern: 'variable',
  },
  {
    categoryName: 'Entertainment',
    applianceTypeName: 'LED TV',
    typicalPowerW: 120,
    powerFactor: 0.7,
    nominalFrequencyHz: 60,
    frequencyTolerance: 0.5,
    thdReference: 18,
    harmonicSignature: '{"3rd":0.15,"5th":0.10}',
    powerPattern: 'constant',
  },
  {
    categoryName: 'Entertainment',
    applianceTypeName: 'Hisense 32-inch 1080p TV',
    typicalPowerW: 58,
    powerFactor: 0.73,
    nominalFrequencyHz: 60,
    frequencyTolerance: 0.5,
    thdReference: 14,
    harmonicSignature: '{"3rd":0.12,"5th":0.07}',
    powerPattern: 'constant',
  },
  {
    categoryName: 'Entertainment',
    applianceTypeName: 'PS4 Pro',
    typicalPowerW: 165,
    powerFactor: 0.93,
    nominalFrequencyHz: 60,
    frequencyTolerance: 0.4,
    thdReference: 5.5,
    harmonicSignature: '{"3rd":0.03,"5th":0.02}',
    powerPattern: 'variable',
  },
  {
    categoryName: 'Lighting',
    applianceTypeName: 'LED Light Bulb',
    typicalPowerW: 12,
    powerFactor: 0.95,
    nominalFrequencyHz: 60,
    frequencyTolerance: 0.3,
    thdReference: 2,
    harmonicSignature: '{"3rd":0.01}',
    powerPattern: 'constant',
  },
  {
    categoryName: 'Computing',
    applianceTypeName: 'Wi-Fi Router',
    typicalPowerW: 18,
    powerFactor: 0.92,
    nominalFrequencyHz: 60,
    frequencyTolerance: 0.3,
    thdReference: 2.5,
    harmonicSignature: '{"3rd":0.01}',
    powerPattern: 'constant',
  },
  {
    categoryName: 'Computing',
    applianceTypeName: 'Laptop Charger',
    typicalPowerW: 65,
    powerFactor: 0.9,
    nominalFrequencyHz: 60,
    frequencyTolerance: 0.3,
    thdReference: 3.2,
    harmonicSignature: '{"3rd":0.02}',
    powerPattern: 'variable',
  },
  {
    categoryName: 'Computing',
    applianceTypeName: 'Desktop Computer',
    typicalPowerW: 250,
    powerFactor: 0.89,
    nominalFrequencyHz: 60,
    frequencyTolerance: 0.4,
    thdReference: 5.5,
    harmonicSignature: '{"3rd":0.03,"5th":0.02}',
    powerPattern: 'variable',
  },
  {
    categoryName: 'Computing',
    applianceTypeName: 'Gaming PC (Ryzen 5 3600 + RX 6600)',
    typicalPowerW: 285,
    powerFactor: 0.93,
    nominalFrequencyHz: 60,
    frequencyTolerance: 0.4,
    thdReference: 4.8,
    harmonicSignature: '{"3rd":0.03,"5th":0.02}',
    powerPattern: 'variable',
  },
  {
    categoryName: 'Charging',
    applianceTypeName: 'iPad M2 Charger',
    typicalPowerW: 20,
    powerFactor: 0.88,
    nominalFrequencyHz: 60,
    frequencyTolerance: 0.3,
    thdReference: 2.8,
    harmonicSignature: '{"3rd":0.02}',
    powerPattern: 'variable',
  },
  {
    categoryName: 'Charging',
    applianceTypeName: 'Redmi Note 10 Charger',
    typicalPowerW: 33,
    powerFactor: 0.88,
    nominalFrequencyHz: 60,
    frequencyTolerance: 0.3,
    thdReference: 3,
    harmonicSignature: '{"3rd":0.02}',
    powerPattern: 'variable',
  },
  {
    categoryName: 'Charging',
    applianceTypeName: 'Redmi Note 13 Charger',
    typicalPowerW: 33,
    powerFactor: 0.89,
    nominalFrequencyHz: 60,
    frequencyTolerance: 0.3,
    thdReference: 2.9,
    harmonicSignature: '{"3rd":0.02}',
    powerPattern: 'variable',
  },
  {
    categoryName: 'Charging',
    applianceTypeName: 'iPhone 12 Charger',
    typicalPowerW: 20,
    powerFactor: 0.87,
    nominalFrequencyHz: 60,
    frequencyTolerance: 0.3,
    thdReference: 2.7,
    harmonicSignature: '{"3rd":0.02}',
    powerPattern: 'variable',
  },
  {
    categoryName: 'Kitchen',
    applianceTypeName: 'Microwave Oven',
    typicalPowerW: 1100,
    powerFactor: 0.98,
    nominalFrequencyHz: 60,
    frequencyTolerance: 0.4,
    thdReference: 4.5,
    harmonicSignature: '{"3rd":0.02}',
    powerPattern: 'constant',
  },
  {
    categoryName: 'Kitchen',
    applianceTypeName: 'Electric Kettle',
    typicalPowerW: 1500,
    powerFactor: 0.99,
    nominalFrequencyHz: 60,
    frequencyTolerance: 0.35,
    thdReference: 2.5,
    harmonicSignature: '{"3rd":0.01}',
    powerPattern: 'constant',
  },
  {
    categoryName: 'Kitchen',
    applianceTypeName: 'Induction Cooker',
    typicalPowerW: 1800,
    powerFactor: 0.96,
    nominalFrequencyHz: 60,
    frequencyTolerance: 0.4,
    thdReference: 6,
    harmonicSignature: '{"3rd":0.03,"5th":0.02}',
    powerPattern: 'variable',
  },
  {
    categoryName: 'Laundry',
    applianceTypeName: 'Washing Machine',
    typicalPowerW: 500,
    powerFactor: 0.85,
    nominalFrequencyHz: 60,
    frequencyTolerance: 0.5,
    thdReference: 9.5,
    harmonicSignature: '{"3rd":0.05,"5th":0.03}',
    powerPattern: 'cyclic',
  },
  {
    categoryName: 'Heating',
    applianceTypeName: 'Water Heater',
    typicalPowerW: 3500,
    powerFactor: 0.99,
    nominalFrequencyHz: 60,
    frequencyTolerance: 0.3,
    thdReference: 2.2,
    harmonicSignature: '{"3rd":0.01}',
    powerPattern: 'constant',
  },
  {
    categoryName: 'Utility',
    applianceTypeName: 'Water Dispenser',
    typicalPowerW: 95,
    powerFactor: 0.88,
    nominalFrequencyHz: 60,
    frequencyTolerance: 0.4,
    thdReference: 4,
    harmonicSignature: '{"3rd":0.02}',
    powerPattern: 'cyclic',
  },
  {
    categoryName: 'Utility',
    applianceTypeName: 'Water Dispenser with Hot',
    typicalPowerW: 420,
    powerFactor: 0.97,
    nominalFrequencyHz: 60,
    frequencyTolerance: 0.4,
    thdReference: 3.5,
    harmonicSignature: '{"3rd":0.02}',
    powerPattern: 'cyclic',
  },
  {
    categoryName: 'Audio',
    applianceTypeName: 'Old JVS Stereo Speaker',
    typicalPowerW: 45,
    powerFactor: 0.84,
    nominalFrequencyHz: 60,
    frequencyTolerance: 0.4,
    thdReference: 7.2,
    harmonicSignature: '{"3rd":0.04,"5th":0.02}',
    powerPattern: 'variable',
  },
  {
    categoryName: 'Audio',
    applianceTypeName: '15W Guitar Amp',
    typicalPowerW: 28,
    powerFactor: 0.84,
    nominalFrequencyHz: 60,
    frequencyTolerance: 0.4,
    thdReference: 6.6,
    harmonicSignature: '{"3rd":0.04,"5th":0.02}',
    powerPattern: 'variable',
  },
];

export const APPLIANCE_CATEGORY_NAMES = Array.from(
  new Set(APPLIANCE_CATALOG.map((entry) => entry.categoryName)),
);
